steps:
  - name: 'python:3.8'
    entrypoint: 'python'
    args: ['-m', 'pip', 'install', '-r', 'requirements.txt']
  - name: 'python:3.8'
    entrypoint: 'python'
    args: ['main.py']

options:
  logging: CLOUD_LOGGING_ONLY  # or NONE if you don't want Cloud Logging
  # logsBucket: cloud_build_buck  # Specify your Cloud Storage bucket name if using Cloud Logging

