steps:
  - name: 'python:3.8'
    entrypoint: 'python'
    args: ['-m', 'pip', 'install', '-r', 'requirements.txt']
  - name: 'python:3.8'
    entrypoint: 'python'
    args: ['main.py']

    # Deployment step for Google Cloud Functions
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'function-1'  # Replace with the name of your Cloud Function
      - '--runtime'
      - 'python38'  # Specify the Python runtime version
      - '--trigger-http'  # Replace with the appropriate trigger type (e.g., '--trigger-topic', '--trigger-bucket', etc.)
      - '--entry-point'
      - 'function_1'  # Specify the correct function name here
    timeout: '300s'  # Adjust the timeout as needed


options:
  logging: CLOUD_LOGGING_ONLY  # or NONE if you don't want Cloud Logging
  # logsBucket: cloud_build_buck  # Specify your Cloud Storage bucket name if using Cloud Logging

